version: '3.8'

services:
  mapos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mapos-app
    restart: always
    environment:
      # Aqui deve ser o nome do serviço abaixo
      - DB_HOSTNAME=db_mapos
      - DB_USERNAME=mapos
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=mapos_db
      - BASE_URL=${BASE_URL}
      - APP_NAME=${APP_NAME}
    networks:
      - mapos-network
    # ports:
    #   - "80"
    depends_on:
      - db_mapos # Ajustado para coincidir com o nome do serviço
    healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:80/"]
          interval: 10s
          timeout: 5s
          retries: 5
  db_mapos:
    image: mysql:5.7
    container_name: mapos-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=mapos_db
      - MYSQL_USER=mapos
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mapos-network

networks:
  mapos-network:
    driver: bridge

volumes:
  mysql_data:
